logging:
  path: /data/logs/@project.artifactId@
  file: /data/logs/@project.artifactId@/@project.artifactId@.log

server:
  servlet:
    session:
      cookie:
        http-only: true
  http2:
    enabled: true
  tomcat:
    accept-count: 100000
    max-connections: 6000
    max-threads: 2000
    min-spare-threads: 150
    remote-ip-header: X-Real-IP
    accesslog:
      enabled: true
      rotate: true
      file-date-format: .yyyy-MM-dd
      directory: /data/logs/@project.artifactId@
      pattern: '%t %{X-Real-IP}i %h %l %u %r %s %b -- %D'
      suffix: ''
  port: 8080
info:
  app:
    name: '@project.name@'
    version: '@project.version@'
    description: '@project.description@'
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
management:
  endpoints:
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: beans,caches,conditions,configprops,env,httptrace,info,integrationgraph,health,metrics,mappings,prometheus,sessions
      base-path: /management
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: full
  health:
    diskspace:
      enabled: false
spring:
  profiles:
    active: #spring.profiles.active#
  application:
    name: '@project.artifactId@'
  http:
    encoding:
      charset: UTF-8
      force: true
  mandatory-file-encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: NON_NULL
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    serialization:
      WRITE_ENUMS_USING_INDEX: false
      WRITE_DATES_AS_TIMESTAMPS: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.bz.gists.mybatis.typehandler
