spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: root
  redis:
    host: 127.0.0.1:6379
    port: 6379
    jedis:
      pool:
        max-wait: 5000
#    cluster:
#      nodes:
#        - 127.0.0.1:6379