spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/database?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    username: root
    password: root
  redis:
    cluster:
      nodes:
        - 127.0.0.1:6379
