# 服务器配置
server:
  prot: 8080

# spring 配置
spring:
  profiles:
    active: '@profiles.active@'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    serialization:
      WRITE_ENUMS_USING_INDEX: true
    default-property-inclusion: NON_NULL
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
  application:
    name: '@project.artifactId@'

# mybatis 配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:mapper/extend/*.xml
  type-aliases-package: com.bz.gists.domain
  configuration:
    map-underscore-to-camel-case: true
